### PR TITLE
Algos

### PR DESCRIPTION
**Pull request by Hunnysunaria**

### CODE REVIEW

**Comment by ALLINONE4298** [comment]
I'm glad to see your contribution. however, i think you have been mistaken. you should commit relative programs in relative  language folder. for e.g. if you have c++ program then that should be in c++ folder only nowhere else. If you commit java program then it should be in java folder only. please follow the organized way that would be better in future.
thanks for your contribution.

**Review by ALLINONE4298 — CHANGES_REQUESTED** [review]
I'm glad to see your contribution. however, i think you have been mistaken. you should commit relative programs in relative  language folder. for e.g. if you have c++ program then that should be in c++ folder only nowhere else. If you commit java program then it should be in java folder only. please follow the organized way that would be better in future.

**Please organized programs in relevant folder.**

thanks again for your contribution.

**Comment by Hunnysunaria** [comment]
I changed the things and added only CPP files which one can practice to sharpen their algorithmic skills. Please check it is showing on your side or not or is it not correct?

**Comment by ALLINONE4298** [comment]
i need you to put java files in java folder only not in c++

**Comment by ALLINONE4298** [comment]
.rb files are also there. remove that.

**Comment by Hunnysunaria** [comment]
is it fine now??

**Comment by Hunnysunaria** [comment]
Java files have no code and not implemented properly that's why I have deleted those.

**Review by ALLINONE4298 — CHANGES_REQUESTED** [review]
i think you accidently deleted Hello.cpp file
and one more thing add your cpp files directly in c++ folder and not create another folder with 1_money_change.

**Pull request merged**
