### PR TITLE
Contribute

### PR DESCRIPTION
**Pull request by jambathehood**
Contributed C program to multiply numbers

### CODE REVIEW

**Review by ALLINONE4298 — CHANGES_REQUESTED** [review]
i know that you owned that three accounts please do as i said.

**Comment by jambathehood** [comment]
Those are my friends whom i assisted. Can u guide me on what should be
changed in my current submission.

**Review by ALLINONE4298 — CHANGES_REQUESTED** [review]
delete that json file.
and edit name of your code file without any gap in between

**Comment by ALLINONE4298** [comment]
use _ underscore instead of spaces

**Pull request merged**
